-- AbhinavOS Supabase Migration SQL

-- 1. Profiles Table
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT,
  personal_code TEXT[],
  level INTEGER DEFAULT 1,
  xp INTEGER DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Daily Logs (Single Source of Truth)
CREATE TABLE daily_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  date DATE UNIQUE DEFAULT CURRENT_DATE,
  sleep_hours REAL DEFAULT 0,
  energy INTEGER DEFAULT 50, -- 0-100
  mood TEXT,
  focus_score INTEGER DEFAULT 0, -- 0-100
  study_hours REAL DEFAULT 0,
  workout_done BOOLEAN DEFAULT FALSE,
  meditation_done BOOLEAN DEFAULT FALSE,
  wake_up_time TEXT, -- e.g. "05:00"
  tasks_completed INTEGER DEFAULT 0,
  total_tasks INTEGER DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Discipline Engine
CREATE TABLE discipline_engine (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  date DATE REFERENCES daily_logs(date) ON DELETE CASCADE,
  daily_score INTEGER DEFAULT 0, -- 0-100
  streak_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Missions
CREATE TABLE missions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  progress_percent INTEGER DEFAULT 0,
  deadline DATE,
  priority TEXT CHECK (priority IN ('low', 'medium', 'high')),
  status TEXT DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Brain Vault
CREATE TABLE brain_vault (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  title TEXT NOT NULL,
  content TEXT,
  category TEXT CHECK (category IN ('Ideas', 'Lessons', 'Business', 'Quotes', 'Reflections')),
  tags TEXT[],
  embedding VECTOR(1536), -- Placeholder for OpenAI/Gemini embeddings
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. Skills
CREATE TABLE skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  skill_name TEXT NOT NULL,
  level INTEGER DEFAULT 1,
  total_practice_minutes INTEGER DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
